// Tree-sitter grammar for tcsh/csh surface syntax.
// Scope: concrete syntax only. Runtime expansion/evaluation is intentionally out of scope.

const PREC = {
  ASSIGN: 1,
  TERNARY: 2,
  OR: 3,
  AND: 4,
  BIT_OR: 5,
  BIT_XOR: 6,
  BIT_AND: 7,
  EQUALITY: 8,
  RELATIONAL: 9,
  SHIFT: 10,
  ADD: 11,
  MULTIPLY: 12,
  PREFIX: 13,
  CALL: 14,
};

module.exports = grammar({
  name: 'tcsh',

  extras: $ => [/[ \t\r\f]+/, $.line_continuation],


  conflicts: $ => [
    [$.word, $.identifier],
    [$.label, $.simple_command],
    [$.case_clause, $.simple_command],
    [$.default_clause, $.simple_command],
    [$.parenthesized_command, $.parenthesized_expression],
    [$.expression, $.word],
    [$.at_statement, $.word],
    [$.word, $.subscript],
    [$.source_file],
  ],

  rules: {
    source_file: $ => seq(
      repeat(choice(
        seq($._statement, repeat1($._terminator)),
        seq($.comment, repeat1($._terminator)),
        $._terminator,
      )),
      optional($._statement),
    ),

    _terminator: _ => token(choice('\n', ';')),
    line_continuation: _ => token(seq('\\', /\r?\n/)),
    comment: _ => token(seq('#', /[^\n]*/)),

    _statement: $ => choice(
      $.if_statement,
      $.foreach_statement,
      $.while_statement,
      $.switch_statement,
      $.repeat_statement,
      $.goto_statement,
      $.onintr_statement,
      $.break_statement,
      $.continue_statement,
      $.breaksw_statement,
      $.at_statement,
      $.label,
      $.command_list,
    ),

    command_list: $ => prec(-1, seq(
      $.and_or_command,
      optional('&'),
    )),

    and_or_command: $ => seq(
      $.pipeline,
      repeat(seq(choice('&&', '||'), $.pipeline)),
    ),

    pipeline: $ => seq(
      $.command,
      repeat(seq(choice('|', '|&'), $.command)),
    ),

    command: $ => choice($.parenthesized_command, $.simple_command),

    parenthesized_command: $ => seq('(', repeat(choice($._statement, $._terminator, $.comment)), ')'),

    simple_command: $ => prec.right(seq(
      repeat($.redirection),
      choice($.builtin_command, $.word),
      repeat(choice($.word, $.builtin_command, $.assignment_word, $.redirection)),
    )),

    builtin_command: $ => choice(
      $.alias_command,
      $.unalias_command,
      $.set_command,
      $.unset_command,
      $.setenv_command,
      $.unsetenv_command,
      $.complete_command,
      $.uncomplete_command,
      $.bindkey_command,
      $.limit_command,
      $.unlimit_command,
      $.source_command,
      $.eval_command,
      $.exec_command,
      $.time_command,
      $.nice_command,
      $.nohup_command,
      $.cd_command,
      $.pushd_command,
      $.popd_command,
      $.dirs_command,
      $.jobs_command,
      $.fg_command,
      $.bg_command,
      $.kill_command,
      $.wait_command,
      $.which_command,
      $.where_command,
      $.rehash_command,
      $.hashstat_command,
      $.history_command,
      $.echo_command,
      $.printf_command,
      $.glob_command,
      $.logout_command,
      $.login_command,
      $.exit_command,
      $.return_command,
      $.shift_command,
      $.umask_command,
      $.sched_command,
    ),

    alias_command: _ => 'alias',
    unalias_command: _ => 'unalias',
    set_command: _ => 'set',
    unset_command: _ => 'unset',
    setenv_command: _ => 'setenv',
    unsetenv_command: _ => 'unsetenv',
    complete_command: _ => 'complete',
    uncomplete_command: _ => 'uncomplete',
    bindkey_command: _ => 'bindkey',
    limit_command: _ => 'limit',
    unlimit_command: _ => 'unlimit',
    source_command: _ => choice('source', '.'),
    eval_command: _ => 'eval',
    exec_command: _ => 'exec',
    time_command: _ => 'time',
    nice_command: _ => 'nice',
    nohup_command: _ => 'nohup',
    cd_command: _ => choice('cd', 'chdir'),
    pushd_command: _ => 'pushd',
    popd_command: _ => 'popd',
    dirs_command: _ => 'dirs',
    jobs_command: _ => 'jobs',
    fg_command: _ => 'fg',
    bg_command: _ => 'bg',
    kill_command: _ => 'kill',
    wait_command: _ => 'wait',
    which_command: _ => 'which',
    where_command: _ => 'where',
    rehash_command: _ => 'rehash',
    hashstat_command: _ => 'hashstat',
    history_command: _ => 'history',
    echo_command: _ => 'echo',
    printf_command: _ => 'printf',
    glob_command: _ => 'glob',
    logout_command: _ => 'logout',
    login_command: _ => 'login',
    exit_command: _ => 'exit',
    return_command: _ => 'return',
    shift_command: _ => 'shift',
    umask_command: _ => 'umask',
    sched_command: _ => 'sched',

    assignment_word: $ => seq($.identifier, optional($.subscript), choice('=', '+=', '-='), choice($.word, $.parenthesized_word_list)),
    parenthesized_word_list: $ => seq('(', repeat(choice($.word, $.comment, $._terminator)), ')'),

    redirection: $ => seq($.redirect_operator, optional('&'), $.word),
    redirect_operator: _ => token(choice('>>&!', '>>&', '>>!', '>&!', '>&', '>>', '>!', '<<', '<', '>')),

    if_statement: $ => prec.right(seq(
      'if', '(', optional($.expression), ')',
      choice(
        seq('then', repeat(choice($._statement, $._terminator, $.comment)), repeat($.else_if_clause), optional($.else_clause), 'endif'),
        $._statement,
      ),
    )),
    else_if_clause: $ => prec(2, prec.right(seq('else', 'if', '(', optional($.expression), ')', 'then', repeat(choice($._statement, $._terminator, $.comment))))),
    else_clause: $ => prec(1, prec.right(seq('else', repeat(choice($._statement, $._terminator, $.comment))))),

    foreach_statement: $ => seq('foreach', field('variable', $.identifier), '(', repeat($.word), ')', repeat(choice($._statement, $._terminator, $.comment)), 'end'),
    while_statement: $ => seq('while', '(', optional($.expression), ')', repeat(choice($._statement, $._terminator, $.comment)), 'end'),
    switch_statement: $ => seq('switch', '(', $.expression, ')', repeat(choice($.case_clause, $.default_clause, $._terminator, $.comment)), 'endsw'),
    case_clause: $ => prec.right(seq('case', field('pattern', $.word), ':', repeat(choice($._statement, $._terminator, $.comment)))),
    default_clause: $ => prec.right(seq('default', ':', repeat(choice($._statement, $._terminator, $.comment)))),
    repeat_statement: $ => prec.right(seq('repeat', $.expression, $._statement)),
    goto_statement: $ => seq('goto', $.word),
    onintr_statement: $ => prec.right(seq('onintr', optional($.word))),
    label: $ => seq(field('name', $.identifier), ':'),
    break_statement: _ => 'break',
    continue_statement: _ => 'continue',
    breaksw_statement: _ => 'breaksw',

    at_statement: $ => prec.right(seq('@', optional($.identifier), optional($.subscript), optional(choice($.assignment_operator, $.update_operator)), optional($.expression))),

    assignment_operator: _ => choice('=', '+=', '-=', '*=', '/=', '%='),
    update_operator: _ => choice('++', '--'),

    expression: $ => choice(
      $.word,
      $.number,
      $.parenthesized_expression,
      $.command_status_expression,
      $.file_test_expression,
      $.unary_expression,
      $.binary_expression,
      $.ternary_expression,
    ),

    parenthesized_expression: $ => seq('(', optional($.expression), ')'),
    command_status_expression: $ => seq('{', repeat(choice($._statement, $._terminator, $.comment)), '}'),
    file_test_expression: $ => prec(PREC.PREFIX, seq($.file_test_operator, $.word)),
    file_test_operator: _ => token(choice('-r', '-w', '-x', '-X', '-e', '-o', '-z', '-s', '-f', '-d', '-l', '-b', '-c', '-p', '-u', '-g', '-k', '-t')),
    unary_expression: $ => prec(PREC.PREFIX, seq(choice('!', '~', '+', '-'), $.expression)),
    binary_expression: $ => choice(
      ...[
        ['||', PREC.OR], ['&&', PREC.AND], ['|', PREC.BIT_OR], ['^', PREC.BIT_XOR], ['&', PREC.BIT_AND],
        ['==', PREC.EQUALITY], ['!=', PREC.EQUALITY], ['=~', PREC.EQUALITY], ['!~', PREC.EQUALITY],
        ['<', PREC.RELATIONAL], ['<=', PREC.RELATIONAL], ['>', PREC.RELATIONAL], ['>=', PREC.RELATIONAL],
        ['<<', PREC.SHIFT], ['>>', PREC.SHIFT], ['+', PREC.ADD], ['-', PREC.ADD],
        ['*', PREC.MULTIPLY], ['/', PREC.MULTIPLY], ['%', PREC.MULTIPLY],
      ].map(([operator, precedence]) => prec.left(precedence, seq($.expression, operator, $.expression)))
    ),
    ternary_expression: $ => prec.right(PREC.TERNARY, seq($.expression, '?', $.expression, ':', $.expression)),

    word: $ => choice(
      $.identifier,
      $.number,
      $.bare_word,
      $.option_word,
      $.escape_sequence,
      $.single_quoted_string,
      $.double_quoted_string,
      $.backtick_command_substitution,
      $.variable_substitution,
      $.history_substitution,
      $.glob_pattern,
      $.job_spec,
    ),

    bare_word: _ => token(prec(-1, /[^\s#;|&<>(){}'"`$!\\=+\-]+/)),
    option_word: _ => token(/[+\-][^\s#;|&<>(){}'"`$!\\=]*/),
    identifier: _ => /[A-Za-z_][A-Za-z0-9_]*/,
    number: _ => /[0-9]+/,
    escape_sequence: _ => token(seq('\\', /(.|\r?\n)/)),
    string: $ => choice($.single_quoted_string, $.double_quoted_string),
    single_quoted_string: _ => token(seq("'", repeat(choice(/[^'\\\n]+/, /\\./)), "'")),
    double_quoted_string: $ => seq('"', repeat(choice(token(/[^"\\$`!\n]+/), $.escape_sequence, $.variable_substitution, $.history_substitution, $.backtick_command_substitution)), '"'),
    backtick_command_substitution: $ => seq('`', repeat(choice(token(/[^`\\$!\n]+/), $.escape_sequence, $.variable_substitution, $.history_substitution)), '`'),
    variable_substitution: $ => seq('$', choice($.identifier, $.number, token(/[?#$!<]/), seq('{', token(/[^}\n]+/), '}')), optional($.subscript), repeat($.substitution_modifier)),
    subscript: $ => seq('[', choice($.number, $.identifier, $.word, '*', '$'), optional(seq('-', choice($.number, '$'))), ']'),
    substitution_modifier: _ => token(seq(':', /[A-Za-z&gpqrxstehlut0-9_-]+/)),
    history_substitution: _ => token(seq('!', choice('!', '$', '*', '^', '#', /-?[0-9]+/, /[A-Za-z_][A-Za-z0-9_]*/, seq(':', /[^\s;|&<>(){}'"`]+/)))) ,
    glob_pattern: _ => token(/[A-Za-z0-9_.\/-]*([*?]|\[[^\]\s\n]+\]|\{[^}\s\n]+\})[A-Za-z0-9_.\/-]*/),
    job_spec: _ => token(seq('%', choice('%', '+', '-', /[0-9]+/, /[A-Za-z_][A-Za-z0-9_-]*/))),
  }
});
